import { Playfair_Display, Source_Sans_3 } from 'next/font/google'
import AnimationWrapper from './shared/components/animation-wrapper'

const source_sans_3 = Source_Sans_3({
  subsets: ['latin'],
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={source_sans_3.className}>
      <body className="h-[100dvh]">
        <AnimationWrapper>{children}</AnimationWrapper>
      </body>
    </html>
  )
}
