/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes/index";
import { Route as BlogsIndexImport } from "./routes/blogs/index";
import { Route as BlogsBlogIdImport } from "./routes/blogs/$blogId";

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const BlogsIndexRoute = BlogsIndexImport.update({
  id: "/blogs/",
  path: "/blogs/",
  getParentRoute: () => rootRoute,
} as any);

const BlogsBlogIdRoute = BlogsBlogIdImport.update({
  id: "/blogs/$blogId",
  path: "/blogs/$blogId",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/blogs/$blogId": {
      id: "/blogs/$blogId";
      path: "/blogs/$blogId";
      fullPath: "/blogs/$blogId";
      preLoaderRoute: typeof BlogsBlogIdImport;
      parentRoute: typeof rootRoute;
    };
    "/blogs/": {
      id: "/blogs/";
      path: "/blogs";
      fullPath: "/blogs";
      preLoaderRoute: typeof BlogsIndexImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/blogs/$blogId": typeof BlogsBlogIdRoute;
  "/blogs": typeof BlogsIndexRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/blogs/$blogId": typeof BlogsBlogIdRoute;
  "/blogs": typeof BlogsIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/blogs/$blogId": typeof BlogsBlogIdRoute;
  "/blogs/": typeof BlogsIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/blogs/$blogId" | "/blogs";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/blogs/$blogId" | "/blogs";
  id: "__root__" | "/" | "/blogs/$blogId" | "/blogs/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute;
  BlogsIndexRoute: typeof BlogsIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blogs/$blogId",
        "/blogs/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/blogs/$blogId": {
      "filePath": "blogs/$blogId.tsx"
    },
    "/blogs/": {
      "filePath": "blogs/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
