name: Lint and Prettier Check
on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    container:
      image: node:22
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v3
      - run: npm ci

      - name: Run Prettier
        run: npm run prettier:check

      - name: Run ESLint
        run: npm run lint

      - name: Run Build
        run: npm run build
